version: '3.8'
services:
  app:
    container_name: app
    image: cr.yandex/{{ env.CR_REGISTRY }}/{{ env.CR_REPOSITORY }}:{{ env.IMAGE_TAG }}
    environment:
      - DEBUG=False
      - SECRET_KEY=$${env.SECRET_KEY}
      - PG_DB_NAME=$${env.PG_DB_NAME}
      - PG_DB_USER=$${env.PG_DB_USER}
      - PG_DB_PASSWORD=$${env.PG_DB_PASSWORD}
    ports:
      - '80:80'