version: '3.8'
services:
  app:
    container_name: app
    image: cr.yandex/{{ env.CR_REGISTRY }}/{{ env.CR_REPOSITORY }}:{{ env.IMAGE_TAG }}
    environment:
      - DEBUG=False
      - SECRET_KEY={{env.SECRET_KEY}}
      - DB_ENGINE={{env.DB_ENGINE}}
      - DB_HOST={{env.DB_HOST}}
      - DB_NAME={{env.DB_NAME}}
      - DB_USER={{env.DB_USER}}
      - DB_PASSWORD={{env.DB_PASSWORD}}
      - DJANGO_ALLOWED_HOSTS={{env.DJANGO_ALLOWED_HOSTS}}
    ports:
      - '80:80'
    extra_hosts:
      - "host.docker.internal:host-gateway"