version: '3.8'
services:
  app:
    restart: always
    volumes:
      - static:/vol/web
    ports:
      - 8000:8000
    container_name: app
    build:
      context: .
    # environment:
    #   - DEBUG=False
    #   - SECRET_KEY=os.environ.get('SECRET_KEY')
    #   - DB_ENGINE={{env.DB_ENGINE}}
    #   - DB_HOST=db
    #   - DB_NAME=main_db
    #   - DB_USER={{env.DB_USER}}
    #   - DB_PASSWORD={{env.DB_PASSWORD}}
    #   - DJANGO_ALLOWED_HOSTS={{env.DJANGO_ALLOWED_HOSTS}}
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    image: postgres:13-alpine
    container_name: db
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - PGUSER={{env.DB_USER}}
      - PGPASSWORD={{env.DB_PASSWORD}}
      - PGDATABASE=main_db
      - POSTGRES_USER={{env.DB_USER}}
      - POSTGRES_PASSWORD={{env.DB_PASSWORD}}
      - POSTGRES_DB=main_db
    ports:
      - 5432:5432

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - static:/vol/web

volumes:
  postgres-data:
  static: