version: '3.8'
services:
  app:
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py collectstatic --noinput && 
             python manage.py migrate"
    volumes:
      - static-data/web:/vol/web
    ports:
      - "127.0.0.1:8000:8000"
    container_name: app
    image: cr.yandex/{{ env.CR_REGISTRY }}/{{ env.CR_REPOSITORY }}:{{ env.IMAGE_TAG }}
    environment:
      - DEBUG=False
      - SECRET_KEY={{env.SECRET_KEY}}
      - DB_ENGINE={{env.DB_ENGINE}}
      - DB_HOST=db
      - DB_NAME=main_db
      - DB_USER={{env.DB_USER}}
      - DB_PASSWORD={{env.DB_PASSWORD}}
      - DJANGO_ALLOWED_HOSTS={{env.DJANGO_ALLOWED_HOSTS}}
    depends_on:
      - db
  
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/lib/postgresql/data
    environment:
      - DB_NAME=main_db
      - DB_USER={{env.DB_USER}}
      - DB_PASSWORD={{env.DB_PASSWORD}}

volumes:
  postgres-data:
  static-data: